[package]
name = "PAM-SS"
version = "0.1.0"
edition = "2024"

[dependencies]
rusqlite = { version = "0.31", features = ["bundled"] }

# para nÃ£o mostrar a senha no terminal
rpassword = "7.0"

sha2 = "0.10.9"